version: '3.7'

services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672' # The standard AMQP protocol port
      - '15672:15672' # HTTP management UI
    command:
      - 'rabbitmq-server'
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    networks:
      - composed_network

  postgres:
    container_name: 'postgres'
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/structure.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - composed_network

networks:
  composed_network: {}